name: Test package

on: 
  push:
    branches: [ main ] 
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Install package
      run: |
        pip install -e .
    - name: Unit tests
      run: |
        python -m pytest tests/
        rm -rf tmp/
